version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    command: mosquitto -c /mosquitto-no-auth.conf
    networks:
      - iot-network
    restart: unless-stopped

  iot-service:
    build:
      context: ./iot-service
      dockerfile: Dockerfile
    container_name: iot-service
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=/motor/status
      - MQTT_CLIENT_ID=iot-service-01
      - CSV_FILE=data.csv
      - SEND_INTERVAL=1.0
    volumes:
      - ./iot-service/data.csv:/app/data.csv:ro
    networks:
      - iot-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=/motor/status
      - MQTT_CLIENT_ID=backend-service
    networks:
      - iot-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - iot-network
    restart: unless-stopped


  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    environment:
      - HTTP_PORT=4000
    depends_on:
      - mqtt-broker
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge